# GitHub Pages Configuration
title: Blind 75 LeetCode Study Guides
description: Comprehensive study guides for Blind 75 LeetCode problems
author: Your Name
email: your.email@example.com

# Jekyll settings - use commonmark to avoid Liquid conflicts
markdown: CommonMarkGhPages
highlighter: rouge
permalink: /:title/

# Kramdown settings to handle code blocks properly
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  input: GFM

# Disable Liquid processing for markdown files to avoid conflicts with code syntax
liquid:
  error_mode: warn

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages
  - _posts
  - blind75

# Site settings
url: "https://yourusername.github.io"
baseurl: "/hack_interview"

# Social media
social:
  github: yourusername
  twitter: yourusername
  linkedin: yourusername 