# GitHub Pages Configuration
title: Technical Interview Mastery Hub
description: Master both algorithmic problem-solving and database querying through AI-enhanced active learning methodology
author: Your Name
email: your.email@example.com

# Jekyll settings - use kramdown for GitHub Pages compatibility
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Kramdown settings to handle code blocks properly
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  input: GFM
  hard_wrap: false

# Disable Liquid processing for markdown files to avoid conflicts with code syntax
liquid:
  error_mode: warn

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages
  - _posts
  - blind75

# Site settings
url: "https://zeecares.github.io"
baseurl: "/hack_interview"

# Social media
social:
  github: zeecares
  twitter: zeecares
  linkedin: zeecares 